#!/usr/bin/env python3
"""Regenerate the annotated router in docs/concepts/README.md.

The router is the docs' selection index: one line per page — title (from
SUMMARY.md, the authoritative order) + the page's frontmatter description.
Descriptions live in each page's frontmatter; generating the router from them
makes drift impossible. Run manually after adding/moving pages, and from
scripts/render-to-plugin.sh before every render.

Idempotent: writes only between the router markers in concepts/README.md.
Exits 1 if a listed page is missing a frontmatter description (fix the page).
"""

import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent / "docs"
ROUTER_PAGE = DOCS / "concepts" / "README.md"
BEGIN = "<!-- router:begin — generated by scripts/generate_router.py; do not edit by hand -->"
END = "<!-- router:end -->"


def frontmatter_description(page: Path) -> str | None:
    text = page.read_text()
    m = re.match(r"---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return None
    d = re.search(r"^description:\s*(.+?)(?=\n\S|\n?$)", m.group(1), re.MULTILINE | re.DOTALL)
    if not d:
        return None
    return " ".join(d.group(1).split()).removeprefix(">-").strip()


def build_router() -> str:
    lines_out = ["", "## Every page, and what it answers", ""]
    section = None
    problems = []
    for line in (DOCS / "SUMMARY.md").read_text().splitlines():
        if line.startswith("## "):
            section = line[3:].strip()
            if lines_out[-1] != "":
                lines_out.append("")
            lines_out += [f"### {section}", ""]
            continue
        m = re.match(r"(\s*)\* \[(.+?)\]\((.+?)\)", line)
        if not m:
            continue
        indent, title, path = m.groups()
        if path in ("README.md", "concepts/README.md"):
            continue
        page = DOCS / path
        desc = frontmatter_description(page) if page.is_file() else None
        if desc is None:
            problems.append(path)
            continue
        rel = Path("..") / path if not path.startswith("concepts/") else Path(path).relative_to("concepts")
        prefix = "  " * (len(indent) // 2)
        lines_out.append(f"{prefix}- [{title}]({rel}) — {desc}")
    lines_out.append("")
    if problems:
        sys.exit(f"router: pages missing frontmatter description: {problems}")
    return "\n".join(lines_out)


def main() -> None:
    check_only = "--check" in sys.argv
    text = ROUTER_PAGE.read_text()
    if BEGIN not in text or END not in text:
        sys.exit(f"router markers not found in {ROUTER_PAGE}")
    new = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        BEGIN + "\n" + build_router() + "\n" + END,
        text, flags=re.DOTALL,
    )
    if new == text:
        print("router up to date")
    elif check_only:
        sys.exit("router is stale — run scripts/generate_router.py")
    else:
        ROUTER_PAGE.write_text(new)
        print("router regenerated")


if __name__ == "__main__":
    main()
