#!/usr/bin/env python3
"""Regenerate the annotated router in docs/concepts/README.md.

The router is the docs' selection index: one line per page — title (from
SUMMARY.md, the authoritative order) + the page's frontmatter description.
Descriptions live in each page's frontmatter; generating the router from them
makes drift impossible. Run manually after adding/moving pages, and from
scripts/render-to-plugin.sh before every render.

Idempotent: writes only between the router markers in concepts/README.md.
Exits 1 if a listed page is missing a frontmatter description (fix the page).
"""

import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent / "docs"
ROUTER_PAGE = DOCS / "concepts" / "README.md"
REFERENCE = DOCS / "context-reference"
# Section order for the reference's map — the one editorial choice the pages
# can't carry themselves, since it is about their relationship, not any one page.
GROUP_ORDER = ["The problem", "The levers", "The rules of truth", "The guards", "The dispatch"]
BEGIN = "<!-- router:begin — generated by scripts/generate_router.py; do not edit by hand -->"
END = "<!-- router:end -->"


def frontmatter_description(page: Path) -> str | None:
    text = page.read_text()
    m = re.match(r"---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return None
    d = re.search(r"^description:\s*(.+?)(?=\n\S|\n?$)", m.group(1), re.MULTILINE | re.DOTALL)
    if not d:
        return None
    return " ".join(d.group(1).split()).removeprefix(">-").strip()


def build_router() -> str:
    lines_out = ["", "## Every page, and what it answers", ""]
    section = None
    problems = []
    for line in (DOCS / "SUMMARY.md").read_text().splitlines():
        if line.startswith("## "):
            section = line[3:].strip()
            if lines_out[-1] != "":
                lines_out.append("")
            lines_out += [f"### {section}", ""]
            continue
        m = re.match(r"(\s*)\* \[(.+?)\]\((.+?)\)", line)
        if not m:
            continue
        indent, title, path = m.groups()
        if path in ("README.md", "concepts/README.md"):
            continue
        # The context reference is a second tier that indexes itself: its own
        # README maps the tree, each concept page names the trigger for its deep
        # page. Listing all 41 here would cost this always-read router ~9.7K
        # characters for pages that answer how context behaves, not what the
        # semantic layer is — so the router carries the entrance and stops.
        if path.startswith("context-reference/") and path != "context-reference/README.md":
            continue
        page = DOCS / path
        desc = frontmatter_description(page) if page.is_file() else None
        if desc is None:
            problems.append(path)
            continue
        rel = Path("..") / path if not path.startswith("concepts/") else Path(path).relative_to("concepts")
        prefix = "  " * (len(indent) // 2)
        lines_out.append(f"{prefix}- [{title}]({rel}) — {desc}")
    lines_out.append("")
    if problems:
        sys.exit(f"router: pages missing frontmatter description: {problems}")
    return "\n".join(lines_out)


def frontmatter_field(page: Path, field: str) -> str | None:
    m = re.match(r"---\n(.*?)\n---\n", page.read_text(), re.DOTALL)
    if not m:
        return None
    f = re.search(rf"^{field}:\s*(.+?)$", m.group(1), re.MULTILINE)
    return " ".join(f.group(1).split()) if f else None


def build_reference_map() -> str:
    """The context reference's own map, from the same frontmatter the router reads.

    The reference is a second tier the router only points at, so it needs an
    index of its own — but a hand-written one is a second description per page,
    and two descriptions of one page drift (the failure `one-concept-one-home`
    describes). Every column here is generated: the concept's line from its
    `description`, its section from `group`, the escalation trigger from the
    deep page's `when` — each fact stated once, where it belongs.
    """
    groups: dict[str, list[str]] = {}
    problems = []
    for page in sorted((REFERENCE / "concepts").glob("*.md")):
        desc = frontmatter_description(page)
        group = frontmatter_field(page, "group")
        deep = REFERENCE / "deep" / page.name
        when = frontmatter_field(deep, "when") if deep.is_file() else None
        if not (desc and group and when):
            problems.append(f"{page.name} (description={bool(desc)} group={bool(group)} when={bool(when)})")
            continue
        groups.setdefault(group, []).append(
            f"| [{page.stem}](concepts/{page.name}) | {desc} | {when} |"
        )
    if problems:
        sys.exit(f"reference map: pages missing frontmatter: {problems}")
    unknown = set(groups) - set(GROUP_ORDER)
    if unknown:
        sys.exit(f"reference map: unknown group(s) {sorted(unknown)} — add to GROUP_ORDER")
    out = []
    for group in GROUP_ORDER:
        if group not in groups:
            continue
        out += ["", f"### {group}", "| Concept | One line | Open the deep page when |", "|---|---|---|"]
        out += groups[group]
    out.append("")
    return "\n".join(out)


def regenerate(page: Path, body: str, check_only: bool, label: str) -> bool:
    text = page.read_text()
    if BEGIN not in text or END not in text:
        sys.exit(f"{label} markers not found in {page}")
    new = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        BEGIN + "\n" + body + "\n" + END,
        text, flags=re.DOTALL,
    )
    if new == text:
        print(f"{label} up to date")
        return False
    if check_only:
        sys.exit(f"{label} is stale — run scripts/generate_router.py")
    page.write_text(new)
    print(f"{label} regenerated")
    return True


def main() -> None:
    check_only = "--check" in sys.argv
    regenerate(ROUTER_PAGE, build_router(), check_only, "router")
    if REFERENCE.is_dir():
        regenerate(REFERENCE / "README.md", build_reference_map(), check_only, "reference map")


if __name__ == "__main__":
    main()
